#!/bin/bash

cd ~

# Install other packages
brew install git
brew install the_silver_searcher
brew install ctags-exuberant

# Install python packages
sudo easy_install pip
sudo pip install virtualenv
sudo pip install virtualenvwrapper --ignore-installed

# Install Oh My Zsh
if [ -d ".oh-my-zsh" ]; then
    cd .oh-my-zsh && git pull origin master && cd ~
else
    sh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"
fi

# Clone dotfiles repo
if [ -d "dotfiles" ]; then
    cd dotfiles && git pull origin master && cd ~
else
    git clone https://github.com/scubedoo187/dotfiles.git dotfiles
fi

# Backup old files
mkdir -p .old_dotfiles
[ -d ".vim" ] && mv .vim .old_dotfiles
[ -d ".vimrc" ] && mv .vimrc .old_dotfiles
[ -d ".zshrc" ] && mv .zshrc .old_dotfiles

# Link rc files
ln -s dotfiles/vimrc .vimrc
ln -s dotfiles/vim .vim
ln -s dotfiles/zshrc .zshrc

# Install Vundle
if [ -d ".vim/bundle/Vundle.vim" ]; then
    cd .vim/bundle/Vundle.vim && git pull origin master && cd ~
else
    git clone https://github.com/gmarik/Vundle.vim.git .vim/bundle/Vundle.vim
fi

vim +PluginInstall +qall
